dist: xenial
language: java
jdk:
  - openjdk8
services:
  - xvfb
  - mysql
cache:
   directories:
     - $HOME/.m2
install:
before_install:
  - mysql -u root -e "CREATE SCHEMA IF NOT EXISTS biddingdb";
  - mysql -u root -e "CREATE USER IF NOT EXISTS 'bidadmin'@'localhost' IDENTIFIED WITH mysql_native_password BY 'bidpassword'";
  - mysql -u root -e "GRANT ALL ON biddingDB.* TO 'bidadmin'@'localhost'";
  - mysql -u root -e "GRANT ALL ON *.* TO 'bidadmin'@'localhost'";
  - cd BiddingIt
  # Dependencies not included in Maven official respository
  - mvn install:install-file -Dfile="lib/freetts/cmu_time_awb.jar" -DgroupId="com.github.freetts" -DartifactId="cmu_time_awb" -Dversion="1.0" -Dpackaging="jar"
  - mvn install:install-file -Dfile="lib/freetts/cmu_us_kal.jar" -DgroupId="com.github.freetts" -DartifactId="cmu_us_kal" -Dversion="1.0" -Dpackaging="jar"
  - mvn install:install-file -Dfile="lib/freetts/cmudict04.jar" -DgroupId="com.github.freetts" -DartifactId="cmudict04" -Dversion="1.0" -Dpackaging="jar"
  - mvn install:install-file -Dfile="lib/freetts/cmulex.jar" -DgroupId="com.github.freetts" -DartifactId="cmulex" -Dversion="1.0" -Dpackaging="jar"
  - mvn install:install-file -Dfile="lib/freetts/cmutimelex.jar" -DgroupId="com.github.freetts" -DartifactId="cmutimelex" -Dversion="1.0" -Dpackaging="jar"
  - mvn install:install-file -Dfile="lib/freetts/en_us.jar" -DgroupId="com.github.freetts" -DartifactId="en_us" -Dversion="1.0" -Dpackaging="jar"
  - mvn install:install-file -Dfile="lib/freetts/freetts.jar" -DgroupId="com.github.freetts" -DartifactId="freetts" -Dversion="1.0" -Dpackaging="jar"
  - mvn install:install-file -Dfile="lib/freetts/freetts-jsapi10.jar" -DgroupId="com.github.freetts" -DartifactId="freetts-jsapi10" -Dversion="1.0" -Dpackaging="jar"
  - mvn install:install-file -Dfile="lib/freetts/jsapi.jar" -DgroupId="com.github.freetts" -DartifactId="jsapi" -Dversion="1.0" -Dpackaging="jar"
  - mvn install:install-file -Dfile="lib/freetts/mbrola.jar" -DgroupId="com.github.freetts" -DartifactId="mbrola" -Dversion="1.0" -Dpackaging="jar"
