dist: xenial
language: java
jdk:
  - openjdk8
services:
  - xvfb
  - mysql
cache:
   directories:
     - $HOME/.m2
before_install:
  - mysql -u root -e "create database biddingdb";
  - mysql -u root -e "CREATE USER 'bidadmin'@'localhost' IDENTIFIED BY 'bidpassword'";
  - mysql -u root -e "GRANT ALL ON biddingDB.* TO 'bidadmin'@'localhost'";
- rmiregistry -J-Djava.rmi.server.useCodebaseOnly=false &
